### ISSUE TITLE
Download Issues of Data and Pretrained Models.

### ISSUE THREAD

**Issue by Hai-chao-Zhang** [KovenYu/uORF#1]
Thanks for your great work. 
The download link you provide in [README]("https://office365stanford-my.sharepoint.com/:f:/r/personal/koven_stanford_edu/Documents/uorf_data_model?csf=1&web=1&e=q7oN63") needs a Stanford SharePoint account to log in, which makes us cannot access outside. I try to use a personal account or my institution account to access it, but it didn't work.

Could you please solve this or upload it to google drive? Thanks.

**Comment by KovenYu** [comment]
@Hai-chao-Zhang 
Thanks for letting me know this! Would you mind trying [this](https://office365stanford-my.sharepoint.com/:f:/g/personal/koven_stanford_edu/Et9SOVcOxOdHilaqfq4Y3PsBsiPGW6NGdbMd2i3tRSB5Dg?e=WRrXIh)?

**Comment by Hai-chao-Zhang** [comment]
Thanks, this issue has been solved.
