### ISSUE TITLE
Information about dataloading

### ISSUE THREAD

**Issue by edwhu** [KovenYu/uORF#2]
Hello,
I am trying to apply uORF to my own dataset, which currently consists only of multiview RGB images.
I noticed in the dataloading code there are many additional files to load aside from the images. It is not clear from the paper which inputs are necessary and what are not.

Could you elaborate on all the different files being loaded in the dataloading code? Like if they are necessary for training the model, if they are for evaluation or debugging, and if they are very useful or not for debugging. This will help me greatly with figuring out if I should generate the corresponding metadata with my custom dataset, or just not use it. 

https://github.com/KovenYu/uORF/blob/main/data/multiscenes_dataset.py

**Comment by KovenYu** [comment]
Thanks for asking! For training you will need to generate (1) multi-view images of training scenes and (2) corresponding extrinsic matrix of each view. Our code currently assumes the same intrinsic parameters across all views for simplicity.

I will update it and write an instruction for training your own dataset in a couple of days!
